version: '3'

services:
  db_postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    user: '$UID:$GID'
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PA_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PA_PASSWORD}
    depends_on:
      - db_postgres  
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin     
